import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/theme-provider";
import { cn } from "@/lib/utils";
import { AppWrapper } from "@/context/AppContext";
// import { MobileMenu } from "@/components/menu/MobileMenu";
// import { Menu } from "@/components/menu/Menu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cn(
          "antialiased font-sans",
          inter.className
        )} flex flex-col min-h-screen h-screen`}
      >
        <AppWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* <MobileMenu /> */}
            <main className="flex h-full w-full flex-row items-stretch gap-2 p-2">
              {/* <Menu /> */}
              <div className="rounded-lg shadow-lg grow">{children}</div>
            </main>
          </ThemeProvider>
        </AppWrapper>
      </body>
    </html>
  );
}
